### ISSUE TITLE
Multiple meta keys

### ISSUE THREAD

**Issue by iliesh** [milgra/i3-overview#2]
looks good, but how can I change the meta key to use 2 keys to activate it? Like CTRL+meta key?
I was trying 37+133 in the configuration file, but it didn't work for me.

Also, is there any way to move through the windows by using arrow keys?

**Comment by milgra** [comment]
Hi, thanks for using i3-overview! Secondary keys are not supported yet, but I try to add the functionality today, was thinking about it.
For the next/prev workspace part it's already possible with i3, you have to bind keys to workspace next and workspace prev commands in i3's config file.

**Comment by milgra** [comment]
Hi, it's done, please update and add your desired key into config.

**Comment by iliesh** [comment]
Perfect, it's working fine for me.
Thank you
